# Dapr Cron Input Binding - Reminder Scheduler
# Building Block: Bindings (cron)
# Triggers reminder-service every 30 seconds to process due reminders
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: cron-reminder
  namespace: default
spec:
  type: bindings.cron
  version: v1
  metadata:
    - name: schedule
      value: "@every 30s"
    - name: direction
      value: "input"
scopes:
  - reminder-service
