# Dapr Pub/Sub Component for Local Development
# Task: P5-T-121
# Simplified configuration for Minikube/local Kafka

apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub
spec:
  type: pubsub.kafka
  version: v1
  metadata:
    # Local Kafka connection (Strimzi)
    - name: brokers
      value: "phase5-kafka-kafka-bootstrap:9092"

    # Consumer configuration
    - name: consumerGroup
      value: "phase5-consumers"

    # No authentication for local dev
    - name: authRequired
      value: "false"

    # Initial offset for new consumers
    - name: initialOffset
      value: "oldest"

    # Disable consumer auto-commit for reliability
    - name: disableAutoCommit
      value: "true"

---
# Subscription with Dead Letter Queue for Task Events
apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: task-events-subscription
spec:
  pubsubname: pubsub
  topic: task-events
  routes:
    default: /events/task
  deadLetterTopic: task-events-dlq

---
# Subscription with Dead Letter Queue for Reminder Events
apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: reminder-events-subscription
spec:
  pubsubname: pubsub
  topic: reminder-events
  routes:
    default: /events/reminder
  deadLetterTopic: reminder-events-dlq

---
# Subscription with Dead Letter Queue for Recurrence Events
apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: recurrence-events-subscription
spec:
  pubsubname: pubsub
  topic: recurrence-events
  routes:
    default: /events/recurrence
  deadLetterTopic: recurrence-events-dlq
