# Dapr Secret Store Component (Kubernetes)
# Building Block: Secrets Management
# Services fetch DB credentials and sensitive config via Dapr Secrets API
# instead of reading environment variables directly
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: kubernetes-secrets
  namespace: default
spec:
  type: secretstores.kubernetes
  version: v1
  metadata: []
scopes:
  - chatbot
  - task-service
  - reminder-service
  - recurrence-service
  - audit-service
---
# Local development secret store (file-based)
# Used when running outside Kubernetes (Docker Compose, local dev)
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: local-secrets
  namespace: default
spec:
  type: secretstores.local.file
  version: v1
  metadata:
    - name: secretsFile
      value: "/dapr/secrets/secrets.json"
    - name: nestedSeparator
      value: ":"
scopes:
  - chatbot
  - task-service
  - reminder-service
  - recurrence-service
  - audit-service
